server:
  port: 8080
#  forward-headers-strategy: framework
spring:
  main:
    web-application-type: reactive # 呵呵呵
    allow-bean-definition-overriding: true # 为什么啊，我服了

logging:
  level:
    org.springframework.cloud.gateway: ${cumt-forum.logging.level}
