server:
  port: 8085

spring:
  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 10GB


minio:
  url: ${cumt-forum.minio.url}
  accessKey: ${cumt-forum.minio.accessKey}
  secretKey: ${cumt-forum.minio.secretKey}
  bucketName: ${cumt-forum.minio.bucketName}