spring:
  datasource:
    url: jdbc:mysql://${cumt-forum.db.host}:3306/${cumt-forum.db.schema}?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${cumt-forum.db.username}
    password: ${cumt-forum.db.pw}
  data:
    redis:
      host: ${cumt-forum.redis.host}
      port: ${cumt-forum.redis.port}
      password: ${cumt-forum.redis.password}
      timeout: ${cumt-forum.redis.timeout}
      database: ${cumt-forum.redis.database}