cumt-forum:
  db:
    host: mysql
    pw: 1005
  redis:
    host: redis
    port: 6379
    password: 1005   # Redis服务器密码（可选）
    timeout: 6000  # 连接超时，单位为毫秒
    database: 0
  knife4j:
    basic:
      username: root
      password: 1005
  gpt:
    uri: gpt
    port: 5000
  milvus:
    uri: milvus-standalone
    port: 19530