cumt-forum:
  db:
    host: localhost # 修改为你自己的虚拟机IP地址
    pw: 1005 # 修改为docker中的MySQL密码
  redis:
    host: localhost
    port: 6379
    password: 1005   # Redis服务器密码（可选）
    timeout: 6000  # 连接超时，单位为毫秒
    database: 2
  knife4j:
    basic:
      username: root
      password: 1005
  gpt:
    uri: ws://localhost
    port: 8765
  milvus:
    uri: http://192.168.200.130
    port: 19530