server:
  port: 1005
spring:
  application:
    name: api-doc
  profiles:
    active: dev

knife4j:
  enableAggregation: true
  nacos:
    enable: true
    serviceUrl: ${cumt-forum.knife4j.nacos.url}
    serviceAuth:
      enable: true
      username: ${cumt-forum.knife4j.nacos.username}
      password: ${cumt-forum.knife4j.nacos.password}
    routeAuth:
      enable: true
      username: ${cumt-forum.knife4j.username}
      password: ${cumt-forum.knife4j.password}
    routes:
      - name: 鉴权服务
        serviceName: auth-service
        debug-url: ${cumt-forum.knife4j.debug-url}
        location: ${cumt-forum.knife4j.location}
      - name: 用户服务
        serviceName: user-service
        debug-url: ${cumt-forum.knife4j.debug-url}
        location: ${cumt-forum.knife4j.location}
      - name: 帖子服务
        serviceName: post-service
        debug-url: ${cumt-forum.knife4j.debug-url}
        location: ${cumt-forum.knife4j.location}
      - name: 点赞服务
        serviceName: like-service
        debug-url: ${cumt-forum.knife4j.debug-url}
        location: ${cumt-forum.knife4j.location}
      - name: 评论服务
        serviceName: comment-service
        debug-url: ${cumt-forum.knife4j.debug-url}
        location: ${cumt-forum.knife4j.location}
      #      - name: 论坛服务
      #        serviceName: forum-service
      #        debug-url: ${cumt-forum.knife4j.debug-url}
      #        location: ${cumt-forum.knife4j.location}
      - name: 对象存储服务
        serviceName: oss-service
        debug-url: ${cumt-forum.knife4j.debug-url}
        location: ${cumt-forum.knife4j.location}
      - name: GPT服务
        serviceName: gpt-service
        debug-url: ${cumt-forum.knife4j.debug-url}
        location: ${cumt-forum.knife4j.location}