server:
  port: 1005
spring:
  application:
    name: api-doc

knife4j:
  enableAggregation: true
  nacos:
    enable: true
    serviceUrl: http://192.168.200.130:8848/nacos/
    serviceAuth:
      enable: true
      username: nacos
      password: nacos
    routeAuth:
      enable: true
      username: root
      password: 1005

    routes:
      - name: GPT服务
        serviceName: gpt-service
        groupName:
        namespaceId:
        clusters:
        location: /v3/api-docs
        swaggerVersion: 2.0
        routeAuth:
          enable: false
          username: root
          password: 1005
      - name: 用户服务
        serviceName: user-service
        groupName:
        namespaceId:
        clusters:
        location: /v3/api-docs
        swaggerVersion: 2.0
        routeAuth:
          enable: false
          username: root
          password: 1005