metadata:
  - appName: ''
    dataId: shared-seata.yaml
    desc: Seata的共享配置
    group: DEFAULT_GROUP
    type: yaml
  - appName: ''
    dataId: shared-swagger.yaml
    desc: Swagger的共享配置
    group: DEFAULT_GROUP
    type: yaml
  - appName: ''
    dataId: shared-db.yaml
    desc: 数据库的共享配置
    group: DEFAULT_GROUP
    type: yaml
  - appName: ''
    dataId: shared-log.yaml
    desc: log的共享配置
    group: DEFAULT_GROUP
    type: yaml
  - appName: ''
    dataId: shared-mp.yaml
    desc: MyBatisPlus的共享配置
    group: DEFAULT_GROUP
    type: yaml
  - appName: ''
    dataId: shared-spring.yaml
    desc: Spring的共享配置
    group: DEFAULT_GROUP
    type: yaml
  - appName: ''
    dataId: shared-gpt.yaml
    desc: GPT的共享配置
    group: DEFAULT_GROUP
    type: yaml
  - appName: ''
    dataId: shared-feign.yaml
    desc: Feign的共享配置
    group: DEFAULT_GROUP
    type: yaml
