metadata:
- appName: ''
  dataId: shared-seata.yaml
  desc: Seata的共享配置
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: shared-swagger.yaml
  desc: Swagger的共享配置
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: shared-db.yaml
  desc: 数据库的共享配置
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: shared-log.yaml
  desc: log的共享配置
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: shared-mp.yaml
  desc: MyBatisPlus的共享配置
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: shared-spring.yaml
  desc: Spring的共享配置
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: shared-gpt.yaml
  desc: GPT的共享配置
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: shared-feign.yaml
  desc: Feign的共享配置
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: gateway-routes.json
  desc: ''
  group: DEFAULT_GROUP
  type: json
- appName: ''
  dataId: shared-jwt.yaml
  desc: JWT的共享配置
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: gateway-exclude.yaml
  desc: Gateway网关排除路径配置
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: shared-satoken.yaml
  desc: sa-token的共享配置
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: shared-redis.yaml
  desc: Redis的共享配置
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: shared-email.yaml
  desc: Email的共享配置
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: shared-mongodb.yaml
  desc: 共享的MongoDB配置
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: shared-rocketmq.yaml
  desc: 共享的RocketMQ配置
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: shared-third-party.yaml
  desc: 共享的第三方和配置
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: shared-baidu.yaml
  desc: 共享的百度配置
  group: DEFAULT_GROUP
  type: yaml
