cumt-forum:
  db:
    host: localhost
    port: 3306
    schema: gpt
    username: root
    pw: 1005
  redis:
    host: localhost
    port: 6379
    password: 1005   # Redis服务器密码（可选）
    timeout: 6000  # 连接超时，单位为毫秒
    database: 2
  knife4j:
    basic:
      username: root
      password: 1005
  seata:
    nacos:
      server-addr: localhost:8848
  gpt:
    ws:
      host: ws://localhost
      port: 8765
    http:
      host: localhost
      port: 5000