cumt-forum:
  db:
    host: 192.168.200.130
    pw: 1005
  redis:
    host: localhost
    port: 6379
    password: 1005   # Redis服务器密码（可选）
    timeout: 6000  # 连接超时，单位为毫秒
  knife4j:
    basic:
      username: root
      password: 1005
  gpt:
    uri: http://localhost
    port: 5000
  milvus:
    uri: http://192.168.200.130
    port: 19530