cumt-forum:
  db:
    host: 192.168.200.130
    schema: gpt
    username: root
    pw: 1005
  redis:
    host: 192.168.200.130
    port: 6379
    password: 1005   # Redis服务器密码（可选）
    timeout: 6000  # 连接超时，单位为毫秒
    database: 0
  knife4j:
    basic:
      username: root
      password: 1005
  seata:
    nacos:
      server-addr: 192.168.200.130:8848
  gpt:
    ws:
      host: ws://localhost
      port: 5000
    http:
      host: localhost
      port: 5000