cumt-forum:
  db:
    host: mysql
    schema: gpt
    username: root
    pw: 1005
  redis:
    host: redis
    port: 6379
    password: 1005   # Redis服务器密码（可选）
    timeout: 6000  # 连接超时，单位为毫秒
    database: 0
  knife4j:
    basic:
      username: root
      password: 1005
  seata:
    nacos:
      server-addr: nacos:8848
  gpt:
    ws:
      host: ws://gpt
      port: 5000
    http:
      host: gpt
      port: 5000